import fs from "fs";
import path from "path";

// Helper type
type LangMap = {
  ur: string;
  ar: string;
  zh: string;
  es: string;
  fr: string;
  de: string;
  hi: string;
  pt: string;
  ru: string;
  ja: string;
  bn: string;
};

// We will construct PHRASE_DATA and WORD_DATA
const PHRASE_DATA: Record<string, LangMap> = {
  // 1. Examiner Room
  "autonomous ielts examiner (auto-ask & 30s recording)": {
    ur: "خود مختار آئی ایل ٹی ایس ممتحن (خودکار سوال اور 30 سیکنڈ ریکارڈنگ)",
    ar: "ممتحن آيلتس الذاتي (طرح تلقائي للأسئلة وتسجيل لمدة 30 ثانية)",
    zh: "自主雅思考官（自动提问与30秒录音）",
    es: "Examinador Autónomo de IELTS (Pregunta Automática y Grabación de 30s)",
    fr: "Examinateur IELTS Autonome (Question Automatique et Enregistrement de 30s)",
    de: "Autonomer IELTS-Prüfer (Automatische Fragen & 30s Aufnahme)",
    hi: "स्वायत्त आईईएलटीएस परीक्षक (स्वचालित प्रश्न और 30 सेकंड रिकॉर्डिंग)",
    pt: "Examinador Autônomo de IELTS (Pergunta Automática e Gravação de 30s)",
    ru: "Автономный экзаменатор IELTS (Авто-вопрос и 30-секундная запись)",
    ja: "自律型IELTS試験官（自動質問＆30秒録音）",
    bn: "স্বায়ত্তশাসিত আইইএলটিএস পরীক্ষক (স্বয়ংক্রিয় প্রশ্ন এবং ৩০ সেকেন্ড রেকর্ডিং)"
  },
  "live simulation": {
    ur: "براہ راست نقل (لائیو سمولیشن)",
    ar: "محاكاة حية وتفاعلية",
    zh: "实况真实模拟",
    es: "Simulación en Vivo",
    fr: "Simulation en Direct",
    de: "Live-Simulation",
    hi: "लाइव सिमुलेशन",
    pt: "Simulação ao Vivo",
    ru: "Живая симуляция",
    ja: "リアルタイム実況シミュレーション",
    bn: "সরাসরি সিমুলেশন"
  },
  "the examiner speaks the question aloud, opens your microphone automatically for": {
    ur: "ممتحن سوال بلند آواز میں بولتا ہے، خودکار طور پر آپ کا مائیکروفون کھولتا ہے برائے",
    ar: "ينطق الممتحن السؤال بصوت مسموع، ويفتح الميكروفون تلقائياً لمدة",
    zh: "考官大声朗读题目，并自动开启您的麦克风进行",
    es: "El examinador lee la pregunta en voz alta y abre su micrófono automáticamente durante",
    fr: "L'examinateur lit la question à voix haute et active automatiquement votre microphone pendant",
    de: "Der Prüfer liest die Frage laut vor und schaltet Ihr Mikrofon automatisch frei für",
    hi: "परीक्षक जोर से प्रश्न बोलता है, और स्वचालित रूप से आपका माइक्रोफ़ोन खोलता है",
    pt: "O examinador lê a pergunta em voz alta e ativa automaticamente o microfone por",
    ru: "Экзаменатор произносит вопрос вслух и автоматически включает микрофон на",
    ja: "試験官が質問を音読し、自動的にマイクをオンにして以下の時間録音します：",
    bn: "পরীক্ষক উচ্চস্বরে প্রশ্নটি পাঠ করেন এবং স্বয়ংক্রিয়ভাবে মাইক্রোফোন চালু করেন"
  },
  "30 seconds": {
    ur: "30 سیکنڈ",
    ar: "30 ثانية",
    zh: "30秒",
    es: "30 segundos",
    fr: "30 secondes",
    de: "30 Sekunden",
    hi: "30 सेकंड",
    pt: "30 segundos",
    ru: "30 секунд",
    ja: "30秒間",
    bn: "৩০ সেকেন্ড"
  },
  ", closes recording, and advances to the next question.": {
    ur: "، ریکارڈنگ بند کرتا ہے، اور اگلے سوال پر منتقل ہو جاتا ہے۔",
    ar: "، ثم يغلق التسجيل وينتقل فوراً إلى السؤال التالي.",
    zh: "，停止录音并自动进入下一个问题。",
    es: ", finaliza la grabación y avanza a la siguiente pregunta.",
    fr: ", ferme l'enregistrement et passe à la question suivante.",
    de: ", beendet die Aufnahme und geht zur nächsten Frage über.",
    hi: ", रिकॉर्डिंग बंद करता है, और अगले प्रश्न पर आगे बढ़ता है।",
    pt: ", encerra a gravação e avança para a próxima pergunta.",
    ru: ", завершает запись и переходит к следующему вопросу.",
    ja: "、録音を終了して次の質問へ進みます。",
    bn: ", রেকর্ডিং বন্ধ করে এবং পরবর্তী প্রশ্নে অগ্রসর হয়।"
  },
  "pause auto-mode": {
    ur: "خودکار موڈ روکیں",
    ar: "إيقاف الوضع التلقائي مؤقتاً",
    zh: "暂停自动模式",
    es: "Pausar Modo Automático",
    fr: "Mettre en Pause le Mode Auto",
    de: "Auto-Modus Pausieren",
    hi: "स्वचालित मोड रोकें",
    pt: "Pausar Modo Automático",
    ru: "Приостановить авто-режим",
    ja: "自動モードを一時停止",
    bn: "স্বয়ংক্রিয় মোড বিরতি দিন"
  },
  "resume auto-mode": {
    ur: "خودکار موڈ جاری رکھیں",
    ar: "استئناف الوضع التلقائي",
    zh: "恢复自动模式",
    es: "Reanudar Modo Automático",
    fr: "Reprendre le Mode Auto",
    de: "Auto-Modus Fortsetzen",
    hi: "स्वचालित मोड जारी रखें",
    pt: "Retomar Modo Automático",
    ru: "Возобновить авто-режим",
    ja: "自動モードを再開",
    bn: "স্বয়ংক্রিয় মোড পুনরায় শুরু করুন"
  },
  "current question prompt": {
    ur: "موجودہ سوال کی ہدایت",
    ar: "نص السؤال الحالي",
    zh: "当前问题提示",
    es: "Pregunta Actual",
    fr: "Question Actuelle",
    de: "Aktuelle Fragenstellung",
    hi: "वर्तमान प्रश्न निर्देश",
    pt: "Instrução da Pergunta Atual",
    ru: "Текущий вопрос экзаменатора",
    ja: "現在の質問プロンプト",
    bn: "বর্তমান প্রশ্নের নির্দেশনা"
  },
  "examiner is speaking:": {
    ur: "ممتحن بول رہا ہے:",
    ar: "الممتحن يتحدث الآن:",
    zh: "考官正在讲话：",
    es: "El examinador está hablando:",
    fr: "L'examinateur parle :",
    de: "Prüfer spricht gerade:",
    hi: "परीक्षक बोल रहे हैं:",
    pt: "O examinador está falando:",
    ru: "Экзаменатор говорит:",
    ja: "試験官が話しています：",
    bn: "পরীক্ষক কথা বলছেন:"
  },
  "please listen carefully. recording will automatically begin as soon as the question finishes.": {
    ur: "براہ کرم غور سے سنیں۔ سوال ختم ہوتے ہی ریکارڈنگ خودکار طور پر شروع ہو جائے گی۔",
    ar: "يرجى الاستماع بعناية. سيبدأ التسجيل تلقائياً بمجرد انتهاء طرح السؤال.",
    zh: "请仔细聆听。问题一结束，录音将立即自动开始。",
    es: "Por favor, escuche atentamente. La grabación comenzará automáticamente tan pronto como termine la pregunta.",
    fr: "Veuillez écouter attentivement. L'enregistrement commencera automatiquement dès la fin de la question.",
    de: "Bitte hören Sie aufmerksam zu. Die Aufnahme beginnt automatisch, sobald die Frage beendet ist.",
    hi: "कृपया ध्यान से सुनें। प्रश्न समाप्त होते ही रिकॉर्डिंग स्वचालित रूप से शुरू हो जाएगी।",
    pt: "Por favor, ouça com atenção. A gravação começará automaticamente assim que a pergunta terminar.",
    ru: "Пожалуйста, слушайте внимательно. Запись начнется автоматически сразу после окончания вопроса.",
    ja: "注意深くお聞きください。質問が終了次第、自動的に録音が開始されます。",
    bn: "অনুগ্রহ করে মনোযোগ দিয়ে শুনুন। প্রশ্ন শেষ হওয়ার সাথে সাথেই স্বয়ংক্রিয়ভাবে রেকর্ডিং শুরু হবে।"
  },
  "recording answer live": {
    ur: "جواب کی براہ راست ریکارڈنگ جاری ہے",
    ar: "تسجيل الإجابة المباشرة جاري الآن",
    zh: "正在实时录制您的回答",
    es: "Grabando Respuesta en Vivo",
    fr: "Enregistrement de la Réponse en Direct",
    de: "Live-Aufnahme der Antwort",
    hi: "लाइव उत्तर रिकॉर्ड किया जा रहा है",
    pt: "Gravando Resposta ao Vivo",
    ru: "Идет запись ответа в реальном времени",
    ja: "回答をリアルタイム録音中",
    bn: "সরাসরি উত্তর রেকর্ড করা হচ্ছে"
  },
  "auto-stops at 0 seconds • speak clearly into your microphone": {
    ur: "0 سیکنڈ پر خودکار طور پر بند ہو جائے گا • اپنے مائیکروفون میں واضح طور پر بولیں",
    ar: "يتوقف تلقائياً عند 0 ثانية • تحدث بوضوح في الميكروفون",
    zh: "在0秒时自动停止 • 请对着麦克风清晰作答",
    es: "Se detiene automáticamente en 0 segundos • Hable claramente a su micrófono",
    fr: "S'arrête automatiquement à 0 seconde • Parlez clairement dans votre microphone",
    de: "Stoppt automatisch bei 0 Sekunden • Sprechen Sie deutlich in Ihr Mikrofon",
    hi: "0 सेकंड पर स्वचालित रूप से रुकेगा • अपने माइक्रोफ़ोन में स्पष्ट रूप से बोलें",
    pt: "Para automaticamente em 0 segundos • Fale com clareza ao microfone",
    ru: "Автоматически остановится на 0 секундах • Говорите четко в микрофон",
    ja: "0秒で自動停止します • マイクに向かってはっきりと話してください",
    bn: "০ সেকেন্ডে স্বয়ংক্রিয়ভাবে থামবে • মাইক্রোফোনে পরিষ্কারভাবে কথা বলুন"
  },
  "auto-close in": {
    ur: "خودکار اختتام میں باقی وقت",
    ar: "الإغلاق التلقائي خلال",
    zh: "自动关闭倒计时",
    es: "Cierre automático en",
    fr: "Fermeture automatique dans",
    de: "Automatische Beendigung in",
    hi: "स्वचालित समाप्ति में शेष",
    pt: "Fechamento automático em",
    ru: "Авто-закрытие через",
    ja: "自動終了まで",
    bn: "স্বয়ংক্রিয় সমাপ্তি হতে বাকি"
  },
  "done early (next)": {
    ur: "جلدی مکمل کر لیا (اگلا)",
    ar: "انتهيت مبكراً (التالي)",
    zh: "提前完成（下一题）",
    es: "Terminado antes (Siguiente)",
    fr: "Terminé plus tôt (Suivant)",
    de: "Vorzeitig fertig (Weiter)",
    hi: "जल्दी समाप्त (अगला)",
    pt: "Concluído antes (Próximo)",
    ru: "Готово раньше (Далее)",
    ja: "回答完了（次へ進む）",
    bn: "আগে শেষ হয়েছে (পরবর্তী)"
  },
  "live speech transcript:": {
    ur: "براہ راست تقریر کا متن:",
    ar: "نص الكلام المباشر المنطوق:",
    zh: "实时语音转文字稿：",
    es: "Transcripción de voz en vivo:",
    fr: "Transcription vocale en direct :",
    de: "Live-Sprachtranskript:",
    hi: "लाइव भाषण प्रतिलेखन:",
    pt: "Transcrição de voz ao vivo:",
    ru: "Транскрипция живой речи:",
    ja: "リアルタイム音声文字起こし：",
    bn: "সরাসরি বক্তব্য প্রতিলিপি:"
  },
  "recording complete!": {
    ur: "ریکارڈنگ مکمل ہو گئی!",
    ar: "اكتمل التسجيل بنجاح!",
    zh: "录音完成！",
    es: "¡Grabación completada!",
    fr: "Enregistrement terminé !",
    de: "Aufnahme abgeschlossen!",
    hi: "रिकॉर्डिंग पूरी हुई!",
    pt: "Gravação concluída!",
    ru: "Запись завершена!",
    ja: "録音が完了しました！",
    bn: "রেকর্ডিং সম্পন্ন হয়েছে!"
  },
  "processing response and preparing next question...": {
    ur: "جواب کا تجزیہ کیا جا رہا ہے اور اگلا سوال تیار کیا جا رہا ہے...",
    ar: "جاري معالجة الإجابة وتجهيز السؤال التالي...",
    zh: "正在分析处理您的回答并准备下一个问题...",
    es: "Procesando respuesta y preparando la siguiente pregunta...",
    fr: "Traitement de la réponse et préparation de la question suivante...",
    de: "Antwort wird verarbeitet und nächste Frage vorbereitet...",
    hi: "प्रतिक्रिया का विश्लेषण किया जा रहा है और अगला प्रश्न तैयार किया जा रहा है...",
    pt: "Processando resposta e preparando a próxima pergunta...",
    ru: "Обработка ответа и подготовка следующего вопроса...",
    ja: "回答を分析し、次の質問を準備しています...",
    bn: "উত্তর প্রক্রিয়াকরণ এবং পরবর্তী প্রশ্ন প্রস্তুত করা হচ্ছে..."
  },
  "all questions have been recorded and evaluated under official ielts band descriptors.": {
    ur: "تمام سوالات ریکارڈ کر لیے گئے ہیں اور آئی ایل ٹی ایس کے آفیشل بینڈ معیار کے تحت جانچے گئے ہیں۔",
    ar: "تم تسجيل جميع الأسئلة وتقييمها وفقاً لمعايير درجات آيلتس الرسمية.",
    zh: "所有题目均已录制完毕，并已依据官方雅思评分标准进行评估。",
    es: "Todas las preguntas han sido grabadas y evaluadas según los descriptores oficiales de banda de IELTS.",
    fr: "Toutes les questions ont été enregistrées et évaluées selon les descripteurs officiels de score IELTS.",
    de: "Alle Fragen wurden aufgezeichnet und gemäß den offiziellen IELTS-Band-Deskriptoren bewertet.",
    hi: "सभी प्रश्न रिकॉर्ड कर लिए गए हैं और आधिकारिक आईईएलटीएस बैंड विवरणकों के तहत मूल्यांकन किया गया है।",
    pt: "Todas as perguntas foram gravadas e avaliadas sob os descritores oficiais de banda do IELTS.",
    ru: "Все вопросы записаны и оценены в соответствии с официальными критериями баллов IELTS.",
    ja: "すべての質問が録音され、公式IELTSバンド評価基準に基づいて採点されました。",
    bn: "সমস্ত প্রশ্ন রেকর্ড করা হয়েছে এবং অফিসিয়াল আইইএলটিএস ব্যান্ড মানদণ্ডের অধীনে মূল্যায়ন করা হয়েছে।"
  },
  "proceed to part 2 (cue card)": {
    ur: "حصہ 2 (کیو کارڈ) پر آگے بڑھیں",
    ar: "الانتقال إلى الجزء 2 (بطاقة التحدث)",
    zh: "进入第二部分（话题卡个人陈述）",
    es: "Proceder a la Parte 2 (Tarjeta de Tema)",
    fr: "Passer à la Partie 2 (Carte Sujet)",
    de: "Weiter zu Teil 2 (Cue Card)",
    hi: "भाग 2 (क्यू कार्ड) पर आगे बढ़ें",
    pt: "Avançar para a Parte 2 (Cartão de Tópico)",
    ru: "Перейти к части 2 (Тематическая карточка)",
    ja: "パート2（スピーチカード）へ進む",
    bn: "অংশ ২ (কিউ কার্ড)-এ এগিয়ে যান"
  },
  "proceed to part 3 (discussion)": {
    ur: "حصہ 3 (مباحثہ) پر آگے بڑھیں",
    ar: "الانتقال إلى الجزء 3 (المناقشة التحليلية)",
    zh: "进入第三部分（深入学术讨论）",
    es: "Proceder a la Parte 3 (Discusión)",
    fr: "Passer à la Partie 3 (Discussion Approfondie)",
    de: "Weiter zu Teil 3 (Diskussion)",
    hi: "भाग 3 (चर्चा) पर आगे बढ़ें",
    pt: "Avançar para a Parte 3 (Discussão)",
    ru: "Перейти к части 3 (Двустороннее обсуждение)",
    ja: "パート3（双方向ディスカッション）へ進む",
    bn: "অংশ ৩ (আলোচনা)-এ এগিয়ে যান"
  },
  "finalize & view complete score": {
    ur: "حتمی شکل دیں اور مکمل اسکور دیکھیں",
    ar: "اعتماد النتيجة وعرض التقرير الكامل",
    zh: "完成考试并查看完整成绩单",
    es: "Finalizar y Ver Puntuación Completa",
    fr: "Finaliser et Voir le Score Complet",
    de: "Abschließen & Gesamtergebnis Anzeigen",
    hi: "अंतिम रूप दें और पूरा स्कोर देखें",
    pt: "Finalizar e Ver Pontuação Completa",
    ru: "Завершить и просмотреть итоговый балл",
    ja: "試験を完了して総合スコアを表示",
    bn: "চূড়ান্ত করুন এবং সম্পূর্ণ স্কোর দেখুন"
  },
  "hear british examiner speak question": {
    ur: "برطانوی ممتحن کی آواز میں سوال سنیں",
    ar: "استمع إلى الممتحن البريطاني وهو ينطق السؤال",
    zh: "聆听英国官方考官朗读试题",
    es: "Escuchar al examinador británico decir la pregunta",
    fr: "Écouter l'examinateur britannique énoncer la question",
    de: "Den britischen Prüfer die Frage vorlesen hören",
    hi: "ब्रिटिश परीक्षक को प्रश्न बोलते हुए सुनें",
    pt: "Ouvir o examinador britânico ler a pergunta",
    ru: "Прослушать вопрос в исполнении британского экзаменатора",
    ja: "英国人試験官による質問の音声を聞く",
    bn: "ব্রিটিশ পরীক্ষককে প্রশ্নটি বলতে শুনুন"
  },
  "your recorded speech transcript will appear here automatically...": {
    ur: "آپ کی ریکارڈ شدہ گفتگو کا متن یہاں خودکار طور پر ظاہر ہوگا...",
    ar: "سيظهر نص حديثك المسجل هنا تلقائياً...",
    zh: "您录制的语音文本转录将在此处自动呈现...",
    es: "La transcripción de su voz grabada aparecerá aquí automáticamente...",
    fr: "La transcription de votre discours enregistré apparaîtra ici automatiquement...",
    de: "Ihr aufgezeichnetes Sprachtranskript wird hier automatisch angezeigt...",
    hi: "आपका रिकॉर्ड किया गया भाषण प्रतिलेखन यहां स्वचालित रूप से दिखाई देगा...",
    pt: "A transcrição da sua fala gravada aparecerá aqui automaticamente...",
    ru: "Транскрипция вашей записанной речи появится здесь автоматически...",
    ja: "録音されたスピーチの文字起こしがここに自動表示されます...",
    bn: "আপনার রেকর্ড করা বক্তব্যের প্রতিলিপি এখানে স্বয়ংক্রিয়ভাবে উপস্থিত হবে..."
  },
  "full speech recording permission": {
    ur: "مکمل تقریر ریکارڈنگ کی اجازت",
    ar: "إذن تسجيل الكلام بالكامل",
    zh: "完整语音录制麦克风权限",
    es: "Permiso Completo de Grabación de Voz",
    fr: "Autorisation Complète d'Enregistrement Vocal",
    de: "Vollständige Sprachaufnahme-Berechtigung",
    hi: "पूर्ण भाषण रिकॉर्डिंग अनुमति",
    pt: "Permissão Completa de Gravação de Fala",
    ru: "Разрешение на полную запись речи",
    ja: "スピーチ録音マイク権限",
    bn: "সম্পূর্ণ বক্তৃতা রেকর্ডিং অনুমতি"
  },
  "the examiner introduces themselves and asks questions on familiar topics (home, work, studies, free time).": {
    ur: "ممتحن اپنا تعارف کرواتا ہے اور مانوس موضوعات (گھر، کام، تعلیم، فرصت کا وقت) پر سوالات پوچھتا ہے۔",
    ar: "يقدم الممتحن نفسه ويطرح أسئلة حول موضوعات مألوفة (المنزل، العمل، الدراسة، أوقات الفراغ).",
    zh: "考官进行自我介绍，并就日常熟悉的话题（家庭、工作、学习、闲暇时间）向您提问。",
    es: "El examinador se presenta y hace preguntas sobre temas familiares (hogar, trabajo, estudios, tiempo libre).",
    fr: "L'examinateur se présente et pose des questions sur des sujets familiers (maison, travail, études, loisirs).",
    de: "Der Prüfer stellt sich vor und stellt Fragen zu vertrauten Themen (Zuhause, Arbeit, Studium, Freizeit).",
    hi: "परीक्षक अपना परिचय देता है और परिचित विषयों (घर, काम, पढ़ाई, खाली समय) पर प्रश्न पूछता है।",
    pt: "O examinador se apresenta e faz perguntas sobre tópicos familiares (casa, trabalho, estudos, tempo livre).",
    ru: "Экзаменатор представляется и задает вопросы на знакомые темы (дом, работа, учеба, свободное время).",
    ja: "試験官が自己紹介をし、身近なトピック（住まい、仕事、学業、余暇）について質問します。",
    bn: "পরীক্ষক নিজের পরিচয় দেন এবং পরিচিত বিষয়গুলি (বাড়ি, কাজ, পড়াশোনা, অবসর সময়) সম্পর্কে প্রশ্ন জিজ্ঞাসা করেন।"
  },
  "you will have to talk about the topic for one to two minutes. you have one minute to think about what you are going to say. you can make some notes to help you if you wish.": {
    ur: "آپ کو اس موضوع پر ایک سے دو منٹ تک بات کرنی ہوگی۔ آپ کے پاس سوچنے کے لیے ایک منٹ کا وقت ہے۔ اگر آپ چاہیں تو کچھ نوٹس لکھ سکتے ہیں۔",
    ar: "سيتعين عليك التحدث حول الموضوع لمدة دقيقة إلى دقيقتين. لديك دقيقة واحدة للتفكير فيما ستقوله. يمكنك تدوين بعض الملاحظات لمساعدتك إذا رغبت.",
    zh: "您需要就该话题阐述一至两分钟。您有一分钟的时间思考发言要点。如需帮助，您可以在草稿纸上记录要点。",
    es: "Tendrá que hablar sobre el tema durante uno o dos minutos. Tiene un minuto para pensar en lo que va a decir. Puede tomar notas para ayudarse si lo desea.",
    fr: "Vous devrez parler du sujet pendant une à deux minutes. Vous avez une minute pour réfléchir à ce que vous allez dire. Vous pouvez prendre des notes pour vous aider si vous le souhaitez.",
    de: "Sie müssen ein bis zwei Minuten über das Thema sprechen. Sie haben eine Minute Zeit zum Nachdenken. Sie können sich Notizen machen, wenn Sie möchten.",
    hi: "आपको विषय पर एक से दो मिनट तक बोलना होगा। आपके पास सोचने के लिए एक मिनट का समय है। यदि आप चाहें तो मदद के लिए कुछ नोट्स बना सकते हैं।",
    pt: "Você terá que falar sobre o tópico por um a dois minutos. Você tem um minuto para pensar no que vai dizer. Pode fazer anotações para ajudá-lo, se desejar.",
    ru: "Вам нужно будет говорить на эту тему от одной до двух минут. У вас есть одна минута на подготовку. При желании вы можете сделать заметки.",
    ja: "このトピックについて1〜2分間スピーチしてください。話す内容を考える時間が1分間あります。必要に応じてメモを取っても構いません。",
    bn: "আপনাকে বিষয়টিতে এক থেকে দুই মিনিট কথা বলতে হবে। আপনি কী বলতে যাচ্ছেন তা চিন্তা করার জন্য আপনার কাছে এক মিনিট সময় আছে। আপনি চাইলে সাহায্য করার জন্য কিছু নোট তৈরি করতে পারেন।"
  },
  "recording live microphone audio...": {
    ur: "مائیکروفون سے براہ راست آڈیو ریکارڈ ہو رہی ہے...",
    ar: "جاري تسجيل الصوت المباشر من الميكروفون...",
    zh: "正在通过麦克风实时录音...",
    es: "Grabando audio en vivo del micrófono...",
    fr: "Enregistrement en direct du microphone...",
    de: "Live-Mikrofonaufnahme läuft...",
    hi: "लाइव माइक्रोफ़ोन ऑडियो रिकॉर्ड किया जा रहा है...",
    pt: "Gravando áudio ao vivo do microfone...",
    ru: "Идет запись живого звука с микрофона...",
    ja: "マイク音声をリアルタイム録音中...",
    bn: "সরাসরি মাইক্রোফোন অডিও রেকর্ড করা হচ্ছে..."
  },
  "candidate spoken transcript": {
    ur: "امیدوار کے بولے گئے الفاظ کا متن",
    ar: "نص كلام المرشح المنطوق",
    zh: "考生口语作答转录文本",
    es: "Transcripción del Discurso del Candidato",
    fr: "Transcription Vocale du Candidat",
    de: "Transkript der gesprochenen Kandidatenantwort",
    hi: "उम्मीदवार का बोला गया प्रतिलेखन",
    pt: "Transcrição da Fala do Candidato",
    ru: "Транскрипт устного ответа кандидата",
    ja: "受験者スピーチの文字起こし",
    bn: "প্রার্থীর কথ্য প্রতিলিপি"
  },
  "evaluate text transcript": {
    ur: "متن کے ٹرانسکرپٹ کی جانچ کریں",
    ar: "تقييم النص المكتوب للحديث",
    zh: "评估作答文字记录",
    es: "Evaluar Transcripción de Texto",
    fr: "Évaluer la Transcription Textuelle",
    de: "Texttranskript Bewerten",
    hi: "पाठ प्रतिलेखन का मूल्यांकन करें",
    pt: "Avaliar Transcrição de Texto",
    ru: "Оценить текстовый транскрипт",
    ja: "テキスト書き起こしを採点",
    bn: "টেক্সট ট্রান্সক্রিপ্ট মূল্যায়ন করুন"
  },
  "language & idiomatic enhancements": {
    ur: "زبان اور محاوراتی بہتری",
    ar: "تحسينات اللغة والتعابير الاصطلاحية",
    zh: "地道表达与语言润色建议",
    es: "Mejoras de Lenguaje e Idiomáticas",
    fr: "Améliorations Linguistiques et Idiomatiques",
    de: "Sprachliche & Idiomatische Verbesserungen",
    hi: "भाषा और मुहावरेदार सुधार",
    pt: "Aprimoramentos de Linguagem e Expressões",
    ru: "Улучшение языка и идиоматических выражений",
    ja: "語彙・イディオム表現の改善提案",
    bn: "ভাষা এবং বাগধারা সংক্রান্ত উন্নতি"
  },
  "the examiner asks broader, abstract questions linked to the part 2 theme.": {
    ur: "ممتحن حصہ 2 کے عنوان سے جڑے وسیع اور تجریدی سوالات پوچھتا ہے۔",
    ar: "يطرح الممتحن أسئلة أوسع نطاقاً وأكثر تجريداً ترتبط بموضوع الجزء 2.",
    zh: "考官将就第二部分话题延伸出更宏观、更具学术思辨深度的问题。",
    es: "El examinador hace preguntas más amplias y abstractas vinculadas al tema de la Parte 2.",
    fr: "L'examinateur pose des questions plus larges et abstraites liées au thème de la Partie 2.",
    de: "Der Prüfer stellt breitere, abstrakte Fragen, die mit dem Thema von Teil 2 verknüpft sind.",
    hi: "परीक्षक भाग 2 के विषय से जुड़े व्यापक, अमूर्त प्रश्न पूछता है।",
    pt: "O examinador faz perguntas mais amplas e abstratas ligadas ao tema da Parte 2.",
    ru: "Экзаменатор задает более широкие и абстрактные вопросы, связанные с темой Части 2.",
    ja: "試験官はパート2のテーマに関連した、より広範で抽象的な深層質問を投げかけます。",
    bn: "পরীক্ষক অংশ ২ এর থিমের সাথে যুক্ত আরও বিস্তৃত, বিমূর্ত প্রশ্ন জিজ্ঞাসা করেন।"
  },
  "when you record your audio, click 'convert audio to transcript & evaluate' below to automatically transcribe and evaluate your spoken english with ai...": {
    ur: "جب آپ اپنی آڈیو ریکارڈ کر لیں، تو AI کے ذریعے اپنے بولے گئے انگریزی کی خودکار جانچ کے لیے نیچے دیے گئے بٹن پر کلک کریں...",
    ar: "عند الانتهاء من تسجيل صوتك، انقر على 'تحويل الصوت إلى نص وتقييمه' بالأسفل لتفريغ وتقييم إنجليزيتك المنطوقة بالذكاء الاصطناعي...",
    zh: "录音完毕后，请点击下方的“语音转文字并由AI评估”按钮，系统将自动进行高精度语音转录与官方标准打分...",
    es: "Cuando grabe su audio, haga clic en 'Convertir Audio a Transcripción y Evaluar' a continuación para transcribir y evaluar automáticamente su inglés hablado con IA...",
    fr: "Lorsque vous enregistrez votre audio, cliquez sur 'Convertir l'Audio en Transcription et Évaluer' ci-dessous pour transcrire et évaluer automatiquement votre anglais parlé avec l'IA...",
    de: "Klicken Sie nach der Aufnahme auf 'Audio in Transkript umwandeln & bewerten', um Ihr gesprochenes Englisch automatisch mit KI zu transkribieren und zu bewerten...",
    hi: "जब आप अपना ऑडियो रिकॉर्ड कर लें, तो एआई के साथ अपनी बोली जाने वाली अंग्रेजी का स्वचालित रूप से मूल्यांकन करने के लिए नीचे दिए गए बटन पर क्लिक करें...",
    pt: "Ao gravar seu áudio, clique em 'Converter Áudio em Transcrição e Avaliar' abaixo para transcrever e avaliar automaticamente seu inglês falado com IA...",
    ru: "После записи нажмите «Преобразовать аудио в текст и оценить» ниже, чтобы автоматически расшифровать и оценить вашу устную речь с помощью ИИ...",
    ja: "録音が終わったら、下の「音声を文字起こししてAI採点」をクリックして、発話を自動解析・評価してください...",
    bn: "আপনি যখন আপনার অডিও রেকর্ড করবেন, তখন এআই দিয়ে স্বয়ংক্রিয়ভাবে আপনার কথ্য ইংরেজি প্রতিলিপি এবং মূল্যায়ন করতে নিচে ক্লিক করুন..."
  },
  "auto-saved locally • criteria: tr, cc, lr, gra": {
    ur: "مقامی طور پر محفوظ شدہ • معیارات: TR، CC، LR، GRA",
    ar: "محفوظ محلياً تلقائياً • المعايير: الاستجابة، الترابط، المفردات، الدقة النحوية",
    zh: "已自动本地保存 • 评分四项标准：任务回应、连贯衔接、词汇资源、语法范围与准确性",
    es: "Guardado localmente de forma automática • Criterios: TR, CC, LR, GRA",
    fr: "Sauvegardé localement automatiquement • Critères : TR, CC, LR, GRA",
    de: "Automatisch lokal gespeichert • Kriterien: TR, CC, LR, GRA",
    hi: "स्थानीय रूप से स्वतः सहेजा गया • मानदंड: TR, CC, LR, GRA",
    pt: "Salvo localmente automaticamente • Critérios: TR, CC, LR, GRA",
    ru: "Автоматически сохранено локально • Критерии: TR, CC, LR, GRA",
    ja: "ローカルに自動保存済み • 評価基準：TR（課題の達成度）、CC（一貫性と結束性）、LR（語彙力）、GRA（文法力）",
    bn: "স্বয়ংক্রিয়ভাবে স্থানীয়ভাবে সংরক্ষিত • মানদণ্ড: TR, CC, LR, GRA"
  },
  "high-impact language corrections (before → after)": {
    ur: "انتہائی موثر لسانی اصلاحات (پہلے → بعد میں)",
    ar: "تصحيحات لغوية عالية الأثر (قبل → بعد)",
    zh: "高价值提分表达改写对比（原文 → 满分润色）",
    es: "Correcciones de Lenguaje de Alto Impacto (Antes → Después)",
    fr: "Corrections Linguistiques à Fort Impact (Avant → Après)",
    de: "Hocheffektive Sprachkorrekturen (Vorher → Nachher)",
    hi: "उच्च-प्रभाव भाषा सुधार (पहले → बाद में)",
    pt: "Correções de Linguagem de Alto Impacto (Antes → Depois)",
    ru: "Высокоэффективные языковые исправления (До → После)",
    ja: "高評価に直結する言語添削（修正前 → 修正後）",
    bn: "উচ্চ-প্রভাব ভাষা সংশোধন (আগে → পরে)"
  },
  "actionable steps to reach band 7.5+": {
    ur: "بینڈ 7.5+ تک پہنچنے کے لیے عملی اقدامات",
    ar: "خطوات عملية وقابلة للتطبيق للوصول إلى الدرجة +7.5",
    zh: "突破7.5分及以上的针对性行动方案",
    es: "Pasos Accionables para Alcanzar Banda 7.5+",
    fr: "Étapes Concrètes pour Atteindre la Bande 7.5+",
    de: "Konkrete Schritte zum Erreichen von Band 7.5+",
    hi: "बैंड 7.5+ तक पहुंचने के लिए व्यावहारिक कदम",
    pt: "Passos Acionáveis para Atingir a Faixa 7.5+",
    ru: "Практические шаги для достижения балла 7.5+",
    ja: "バンド7.5以上到達のための具体的ステップ",
    bn: "ব্যান্ড ৭.৫+ পৌঁছানোর জন্য কার্যকরী পদক্ষেপ"
  },
  "read task prompt aloud in selected voice": {
    ur: "منتخب کردہ آواز میں سوال بلند آواز سے سنیں",
    ar: "قراءة نص المهمة بصوت عالٍ بالصوت المحدد",
    zh: "使用所选语音大声朗读题目提示",
    es: "Leer el enunciado de la tarea en voz alta con la voz seleccionada",
    fr: "Lire la consigne de la tâche à voix haute avec la voix sélectionnée",
    de: "Aufgabenstellung mit ausgewählter Stimme laut vorlesen",
    hi: "चयनित आवाज में कार्य निर्देश को जोर से पढ़ें",
    pt: "Ler o enunciado da tarefa em voz alta com a voz selecionada",
    ru: "Прочитать задание вслух выбранным голосом",
    ja: "選択した音声でタスクプロンプトを音読する",
    bn: "নির্বাচিত কণ্ঠে টাস্ক প্রম্পটটি উচ্চস্বরে পড়ুন"
  },
  "dictate with voice in selected language": {
    ur: "منتخب زبان میں آواز سے ڈکٹیٹ کریں",
    ar: "الإملاء الصوتي باللغة المحددة",
    zh: "使用所选语言进行语音听写输入",
    es: "Dictar con voz en el idioma seleccionado",
    fr: "Dicter à la voix dans la langue sélectionnée",
    de: "Per Sprache in ausgewählter Sprache diktieren",
    hi: "चयनित भाषा में आवाज से डिक्टेट करें",
    pt: "Ditar com voz no idioma selecionado",
    ru: "Диктовать голосом на выбранном языке",
    ja: "選択した言語で音声入力・ディクテーションする",
    bn: "নির্বাচিত ভাষায় ভয়েস দিয়ে ডিক্টেশন দিন"
  },
  "listen to passage text read aloud in selected speech language": {
    ur: "منتخب کردہ زبان میں عبارت کا متن بلند آواز سے سنیں",
    ar: "الاستماع إلى نص القطعة مقروءاً بصوت عالٍ باللغة المحددة",
    zh: "用选定的发音语言大声朗读文章内容",
    es: "Escuchar el texto del pasaje leído en voz alta en el idioma seleccionado",
    fr: "Écouter le texte du passage lu à voix haute dans la langue sélectionnée",
    de: "Den Textabschnitt in der ausgewählten Sprache laut vorlesen lassen",
    hi: "चयनित भाषा में गद्यांश पाठ को जोर से पढ़ें",
    pt: "Ouvir o texto do trecho lido em voz alta no idioma selecionado",
    ru: "Слушать чтение текста отрывка вслух на выбранном языке",
    ja: "選択した言語で長文パッセージの音読を聞く",
    bn: "নির্বাচিত ভাষায় অনুচ্ছেদের পাঠটি উচ্চস্বরে শুনুন"
  },
  "type your answer here...": {
    ur: "اپنا جواب یہاں لکھیں...",
    ar: "اكتب إجابتك هنا...",
    zh: "请在此输入您的答案...",
    es: "Escriba su respuesta aquí...",
    fr: "Tapez votre réponse ici...",
    de: "Geben Sie Ihre Antwort hier ein...",
    hi: "अपना उत्तर यहाँ लिखें...",
    pt: "Digite sua resposta aqui...",
    ru: "Введите ваш ответ здесь...",
    ja: "ここに回答を入力してください...",
    bn: "আপনার উত্তর এখানে টাইপ করুন..."
  },
  "type answer here...": {
    ur: "جواب یہاں لکھیں...",
    ar: "اكتب الإجابة هنا...",
    zh: "在此输入答案...",
    es: "Escriba la respuesta aquí...",
    fr: "Tapez la réponse ici...",
    de: "Antwort hier eingeben...",
    hi: "उत्तर यहाँ लिखें...",
    pt: "Digite a resposta aqui...",
    ru: "Введите ответ здесь...",
    ja: "ここに回答を入力...",
    bn: "উত্তর এখানে টাইপ করুন..."
  }
};

console.log("Writing builder script with extended definitions...");
fs.writeFileSync("scripts/full_phrase_data.json", JSON.stringify(PHRASE_DATA, null, 2));
