// Tests 7 to 10 with authentic, diverse academic passages and 40 questions each

export const tests7to10 = [
  {
    id: 7,
    title: "Academic Reading Test 7 • Fungal Networks, Archaeometry & Nanotechnology",
    passages: [
      `[A] Beneath the damp leaf litter of temperate and boreal forests, a subterranean biological web weaves together entire forest canopies. Rather than functioning as isolated organisms locked in ruthless Darwinian competition for light and soil minerals, forest trees are physically linked by mycorrhizal fungal networks—an underground mutualism popular science has dubbed the 'Wood Wide Web'.

[B] The architectural foundation of this subterranean internet consists of microscopic fungal threads known as hyphae, which collectively form expansive mycelial mats. Mycorrhizal fungi penetrate the root tips of trees, forming specialized exchange organs. Because fungi lack chlorophyll, they depend on host trees to supply carbon-rich carbohydrates produced via photosynthesis. In return, the vast surface area of the mycelium absorbs water, phosphorus, and nitrogen from deep soil matrices, delivering these essential nutrients back to tree roots.

[C] In the late 1990s, forest ecologist Dr. Suzanne Simard at the University of British Columbia demonstrated that mycorrhizal networks facilitate inter-species resource sharing. By injecting radioactive carbon isotopes (carbon-14 and carbon-13) into the foliage of paper birch and Douglas fir saplings, Simard tracked bidirectional carbon transfer through mycelial bridges. In spring, when birch seedlings enjoyed full canopy sunlight, they shuttled surplus carbon to shaded fir seedlings; in autumn, when birch lost their leaves, fir trees reversed the flow, returning carbon to their deciduous neighbors.

[D] Beyond basic nutrient barter, mycorrhizal networks function as early-warning communication channels. When a tree is attacked by foliar pests such as aphids or pathogenic fungi, it rapidly transmits chemical and electrical defense signals through the interconnected fungal mycelium. Neighboring undamaged trees receiving these subterranean signals synthesize protective defensive chemicals, such as volatile tannins and protease inhibitors, preemptively fortifying their foliage before the pest swarm arrives.

[E] Recognizing the ecological primacy of fungal networks is transforming forestry practices. Traditional industrial clear-cutting annihilates delicate soil mycelia, turning forest floors into biological deserts that impede reforestation. Modern sustainable silviculture now advocates retaining mature 'hub trees' or 'mother trees' during selective timber harvesting, preserving intact mycorrhizal nodes that nurture regenerating saplings.`,

      `[A] When the Archimedes Palimpsest arrived at the Walters Art Museum in Baltimore in 1998, it appeared to be an ordinary thirteenth-century Byzantine prayer book known as an Euchologion. However, beneath the liturgical religious hymns lay the faint, scraped-away remnants of seven lost mathematical treatises by the third-century BCE Greek geometer Archimedes of Syracuse, including the only surviving Greek copies of 'The Method of Mechanical Theorems' and 'Stomachion'.

[B] The manuscript had suffered catastrophic reuse through palimpsesting—a common medieval practice where expensive animal vellum was washed with acidic lemon juice and scraped with pumice stone so it could be overwritten with new texts. Furthermore, twentieth-century art forgers had painted counterfeit religious miniatures in tempera paint over several folios to inflate the book's black-market sale price, obscuring the erased Archimedean script beneath heavy gold and carbon pigments.

[C] Unlocking these overwritten ancient texts required an unprecedented collaboration between classicists and particle physicists. Initial attempts using standard ultraviolet fluorescence and multispectral camera imaging revealed substantial portions of erased Greek lettering. However, in folios heavily obscured by twentieth-century forger paint or mold, optical photography was entirely blind to the hidden undertext.

[D] The definitive breakthrough occurred at the Stanford Synchrotron Radiation Lightsource (SSRL). Scientists placed individual vellum folios in front of an intense, ultra-focused X-ray beam generated by a particle accelerator. Because Archimedes' original medieval scribes had written using iron-gall ink—a formulation synthesized from crushed oak galls, iron vitriol, and gum arabic—the underlying text contained atomic iron. When excited by synchrotron X-rays, the iron atoms fluoresced, emitting characteristic X-ray wavelengths that penetrated through paint and mold to yield razor-sharp digital images of Archimedes' original mathematical diagrams.

[E] The recovered treatises fundamentally rewritten the history of science. In 'The Method', Archimedes explicitly calculated areas and volumes using concepts of the infinite and infinitesimal, proving that he had anticipated the core foundations of modern integral calculus nearly two thousand years before Sir Isaac Newton and Gottfried Wilhelm Leibniz developed the discipline in seventeenth-century Europe.`,

      `[A] In 1895, Russian astronautics pioneer Konstantin Tsiolkovsky gazed upon the newly constructed Eiffel Tower in Paris and formulated a daring thought experiment: what if humanity could construct a celestial tower reaching all the way into geosynchronous Earth orbit? For more than a century, Tsiolkovsky's space elevator remained pure science fiction, dismissed because no known engineering material possessed the tensile strength required to withstand its own enormous gravitational weight.

[B] The discovery of carbon nanotubes (CNTs) by Japanese physicist Sumio Iijima in 1991 revitalized the space elevator concept. Carbon nanotubes are cylindrical nanostructures composed of carbon atoms arranged in a hexagonal honeycomb lattice, akin to a rolled sheet of single-atom-thick graphene. In laboratory tensile testing, flawless single-walled carbon nanotubes exhibit a theoretical tensile strength exceeding one hundred gigapascals—nearly one hundred times greater than high-strength structural steel—while possessing only a fraction of steel's density.

[C] In a viable space elevator design, a continuous nanotube composite tether would extend roughly 96,000 kilometres from an equatorial ocean platform into outer space, anchored by a massive counterweight, such as a captured asteroid. Climber vehicles powered by beamed laser light would ascend the ribbon at hundreds of kilometres per hour, carrying scientific satellites and human passengers directly into orbit without expending thousands of tons of volatile chemical rocket propellants.

[D] Deploying a space elevator would reduce orbital payload delivery costs by orders of magnitude. While conventional rocket launches cost between $2,000 and $10,000 per kilogram of payload placed in low Earth orbit, space elevator transit could slash launch expenses to less than $100 per kilogram. This economic transformation would make interplanetary space exploration, asteroid mining for rare minerals, and space-based solar power economically viable.

[E] Despite the immense theoretical promise, formidable engineering and nanoscale synthesis hurdles remain. Contemporary chemical vapor deposition reactors can synthesize carbon nanotubes only a few tens of centimetres in length; synthesizing an unbroken, defect-free macroscopic composite cable 96,000 kilometres long is currently beyond global manufacturing capability. Moreover, space debris in low Earth orbit poses catastrophic severing risks, necessitating active tether deflection thrusters and autonomous micro-repair crawlers.`
    ],
    questions: [
      { type: "tfng", q: "Trees in temperate forests compete for soil resources without ever sharing nutrients.", answer: "FALSE" },
      { type: "tfng", q: "Mycorrhizal fungi receive carbohydrates produced by host trees via photosynthesis.", answer: "TRUE" },
      { type: "tfng", q: "Dr. Suzanne Simard used radioactive carbon isotopes to track carbon movement between birch and fir trees.", answer: "TRUE" },
      { type: "tfng", q: "Birch trees sent carbon to fir trees in autumn when the birch leaves had fallen.", answer: "FALSE" },
      { type: "tfng", q: "Trees can send defensive warning signals to neighboring trees through fungal hyphae.", answer: "TRUE" },
      { type: "tfng", q: "Industrial clear-cutting preserves underground mycorrhizal networks better than selective logging.", answer: "FALSE" },
      { type: "tfng", q: "The Canadian government has banned all commercial logging in British Columbia forests.", answer: "NOT GIVEN" },
      { type: "mcq", q: "What is the network of microscopic fungal threads beneath the soil called?", options: ["Pollen tubes", "Mycelium composed of hyphae", "Cambium fibers", "Root stomata"], answer: 1 },
      { type: "mcq", q: "What nutrient do mycorrhizal fungi absorb from soil and deliver to host tree roots?", options: ["Chlorophyll and helium", "Phosphorus, water, and nitrogen", "Pure metallic iron", "Liquid carbon dioxide"], answer: 1 },
      { type: "mcq", q: "Why was the Archimedes manuscript erased in the thirteenth century?", options: ["To hide secret military formulas from invaders", "The vellum parchment was expensive and scraped clean to write a Christian prayer book", "The monastery suffered a devastating ink flood", "The Greek alphabet was outlawed across the Byzantine Empire"], answer: 1 },
      { type: "mcq", q: "Why was particle accelerator X-ray fluorescence able to read the erased Archimedes text beneath paint?", options: ["It melted the gold paint off the pages", "The original ink contained iron atoms that fluoresced when excited by X-rays", "It magnified the letters using cosmic rays", "It converted the vellum into transparent glass"], answer: 1 },
      { type: "completion", q: "Fungi lack chlorophyll and thus rely on trees for carbon produced during ________.", answer: "photosynthesis" },
      { type: "completion", q: "The medieval practice of scraping animal parchment to reuse it is called ________.", answer: "palimpsesting" },

      { type: "tfng", q: "Twentieth-century art forgers painted religious miniatures over Archimedes' mathematical text.", answer: "TRUE" },
      { type: "tfng", q: "Archimedes' treatise 'The Method' revealed that he had anticipated concepts of integral calculus.", answer: "TRUE" },
      { type: "tfng", q: "Sir Isaac Newton was familiar with 'The Method' when he invented calculus in the 1600s.", answer: "FALSE" },
      { type: "tfng", q: "Konstantin Tsiolkovsky was inspired by the Eiffel Tower to imagine a space elevator.", answer: "TRUE" },
      { type: "tfng", q: "Sumio Iijima discovered carbon nanotubes in 1991.", answer: "TRUE" },
      { type: "tfng", q: "High-strength structural steel has greater tensile strength than single-walled carbon nanotubes.", answer: "FALSE" },
      { type: "tfng", q: "Current industrial reactors can easily manufacture defect-free carbon nanotube cables 96,000 kilometres long.", answer: "FALSE" },
      { type: "mcq", q: "How does a space elevator tether maintain tension into space?", options: ["It is tied directly to the Moon's surface", "It extends into space and is anchored by a counterweight like a captured asteroid", "Large helium balloons hold the top of the cable", "Giant anti-gravity magnets repel the upper end"], answer: 1 },
      { type: "mcq", q: "By how much could a space elevator reduce the cost of launching payloads into orbit?", options: ["From $10,000/kg down to less than $100/kg", "By about five percent", "From $50/kg down to $45/kg", "It would increase launch costs tenfold"], answer: 0 },
      { type: "mcq", q: "What major hazard in low Earth orbit threatens the long-term integrity of a space elevator ribbon?", options: ["High atmospheric ozone", "Extreme solar brightness", "Collisions with space debris", "Corrosive rain clouds"], answer: 2 },
      { type: "mcq", q: "What ink ingredient enabled X-ray detection of the ancient Greek text?", options: ["Titanium oxide", "Iron vitriol in iron-gall ink", "Silver nitrate", "Charcoal ash"], answer: 1 },
      { type: "completion", q: "Theoretical tensile strength of single-walled carbon nanotubes exceeds 100 ________.", answer: "gigapascals" },
      { type: "completion", q: "Archimedes of Syracuse lived in the third century ________.", answer: "BCE" },

      { type: "tfng", q: "Carbon nanotubes are composed of carbon atoms arranged in a hexagonal honeycomb lattice.", answer: "TRUE" },
      { type: "tfng", q: "The Archimedes Palimpsest was analyzed at the Stanford Synchrotron Radiation Lightsource.", answer: "TRUE" },
      { type: "tfng", q: "Mycorrhizal defense warnings cause neighboring trees to produce protective tannins.", answer: "TRUE" },
      { type: "tfng", q: "Climber vehicles on a space elevator would burn kerosene rocket fuel to ascend.", answer: "FALSE" },
      { type: "tfng", q: "Mother trees in forests serve as major nodes in mycorrhizal fungal networks.", answer: "TRUE" },
      { type: "tfng", q: "Standard ultraviolet light was able to read all pages covered by modern forger paint.", answer: "FALSE" },
      { type: "tfng", q: "Japan plans to launch the world's first commercial space elevator by 2030.", answer: "NOT GIVEN" },
      { type: "mcq", q: "What type of tree shuttled carbon to Douglas fir seedlings during spring in Dr. Simard's experiments?", options: ["Sitka spruce", "Paper birch", "Redwood", "Lodgepole pine"], answer: 1 },
      { type: "mcq", q: "What is the term given to an ancient recycled parchment that was erased and written over?", options: ["Papyrus scroll", "Palimpsest", "Codex aureus", "Cuneiform prism"], answer: 1 },
      { type: "mcq", q: "What form of energy would power climber vehicles ascending a space elevator ribbon?", options: ["Beamed laser light", "Onboard coal steam boilers", "Wind sails", "Diesel internal combustion engines"], answer: 0 },
      { type: "mcq", q: "Which mathematical discipline was fundamentally anticipated in Archimedes' 'The Method'?", options: ["Spherical trigonometry", "Integral calculus", "Modern probability", "Boolean algebra"], answer: 1 },
      { type: "completion", q: "The underground fungal threads that form mycelial networks are called ________.", answer: "hyphae" },
      { type: "completion", q: "The Japanese physicist who discovered carbon nanotubes in 1991 was Sumio ________.", answer: "Iijima" },
      { type: "completion", q: "In 'The Method', Archimedes calculated volumes using concepts of the infinite and ________.", answer: "infinitesimal" }
    ]
  },
  {
    id: 8,
    title: "Academic Reading Test 8 • Neolithic Agronomy, Volcanology & Diagnostic AI",
    passages: [
      `[A] Perched on a limestone terrace above the Euphrates river basin in modern northern Syria, the prehistoric archaeological settlement of Tell Abu Hureyra preserves one of humanity's most momentous cultural milestones: the transition from nomadic foraging to settled plant cultivation. Spanning the boundary of the Younger Dryas climatic cold snap roughly 12,800 years ago, excavations reveal how abrupt ecological stress prompted hunter-gatherers to domesticate wild cereal grasses.

[B] The botanical revolution centered upon einkorn wheat (Triticum monococcum) and emmer wheat. In wild cereal varieties, the central stem holding the grain cluster—the rachis—is brittle. When the seed head ripens, the brittle rachis naturally shatters in the wind, scattering grains across the soil to guarantee wild propagation. For human foragers, however, a shattering rachis is deeply inefficient, as most grains fall to the ground before they can be harvested.

[C] Archaeobotanical analysis of carbonized cereal grains from Tell Abu Hureyra documents a gradual genetic shift. Mutated plants possessing a non-shattering rachis, where seeds remain firmly attached to the ear until manually threshed, are evolutionary dead-ends in the wild. Yet when prehistoric humans collected grains using bone sickles, they preferentially harvested non-shattering ears, unconsciously selecting and replanting these mutant seeds in prepared garden plots.

[D] Domestication transformed not only plant morphology but human skeletal biology. Bioarchaeological study of human remains across successive occupational strata at Abu Hureyra reveals profound physiological changes. Skeletons from the agricultural period exhibit severe degenerative osteoarthritis in the lumbar vertebrae, knees, and metatarsal foot bones—the physical legacy of spending hours daily kneeling over heavy saddle querns grinding coarse grain into edible flour.

[E] Furthermore, settled agriculture induced demographic shifts. Permanent grain storage granaries provided a dependable caloric surplus, dampening seasonal famine risks and precipitating a rapid rise in fertility rates. However, living in close proximity to domesticated sheep and goats catalyzed the initial emergence of zoonotic infectious diseases, establishing the epidemiological patterns that would govern human civilizations for millennia.`,

      `[A] In April 1815, the volcanic caldera of Mount Tambora on the Indonesian island of Sumbawa detonated in the most catastrophic explosive eruption in recorded human history. Blasting over one hundred cubic kilometres of pulverized rock, pumice, and ash into the atmosphere, the eruption obliterated the surrounding island civilization and ejected tens of millions of tons of sulfur dioxide gas into the stratosphere.

[B] The atmospheric impact of stratospheric volcanic aerosols operates through radiative forcing. While coarse tropospheric ash particles fall back to Earth within days, sulfur dioxide gas reaching the dry stratosphere oxidizes into ultra-fine sulfuric acid aerosol droplets (H2SO4). These microscopic aerosol veils remain suspended in the upper atmosphere for two to three years, scattering incoming shortwave solar radiation back into space while absorbing terrestrial infrared heat.

[C] The resulting global cooling triggered the infamous 'Year Without a Summer' in 1816. Northern Hemisphere average surface temperatures dropped by up to one degree Celsius, causing catastrophic agricultural collapses across Europe and North America. In New England, killing frosts and blizzards occurred in June and July, destroying summer corn crops. Across Western Europe, relentless summer rainstorms rotted wheat fields, causing the continent's last great peacetime famine and widespread food riots.

[D] Beyond immediate agrarian hardship, the Tambora climate perturbation catalyzed unexpected cultural and technological innovations. In Switzerland, confined indoors for weeks by torrential freezing rains at Lake Geneva, eighteen-year-old Mary Shelley responded to a ghost-story writing contest by penning her classic Gothic novel, 'Frankenstein'. Concurrently, in Germany, widespread horse starvation prompted inventor Karl Drais to develop a human-powered two-wheeled wooden mobility machine called the 'Laufmaschine'—the direct mechanical ancestor of the modern bicycle.

[E] Contemporary volcanologists monitor active calderas using satellite interferometric synthetic aperture radar (InSAR) and seismic tremor arrays to detect subterranean magma ascent. While modern civil protection agencies can evacuate vulnerable local populations before major explosive events, humanity remains intrinsically vulnerable to the multi-year global climatic disruption that an ultra-plinian super-eruption would inevitably unleash.`,

      `[A] Within modern hospital oncology and radiology departments, the interpretation of diagnostic imaging—such as computed tomography (CT) scans, magnetic resonance imaging (MRI), and digital mammography—represents one of the most cognitively demanding tasks in clinical medicine. Radiologists must scrutinize thousands of high-resolution image slices per patient shift, searching for subtle micro-calcifications, ground-glass lung opacities, or intracranial hemorrhages that may measure only a few millimeters in diameter.

[B] Over the past decade, the integration of deep learning convolutional neural networks (CNNs) has transformed medical computer vision. Unlike earlier computer-aided detection software that relied upon handcrafted geometric rules, modern deep CNNs are trained end-to-end on millions of annotated medical scans. Through multiple hierarchical layers, the neural network learns to extract abstract mathematical features, detecting malignant patterns that frequently escape the human eye.

[C] In landmark diagnostic benchmark trials published in journals such as 'Nature', advanced AI algorithms demonstrated diagnostic parity with, and in specific modalities exceeded, the accuracy of board-certified radiologists. In screening mammography, AI systems reduced false-positive recalls by over five percent and lowered false-negative missed cancer rates by nearly nine percent. Furthermore, AI models operate continuously without suffering from visual search fatigue, a major contributor to human perceptual error during long hospital shifts.

[D] Despite these empirical successes, clinicians caution against autonomous diagnostic deployment, advocating instead for an augmented intelligence model. Deep learning networks frequently operate as 'black boxes', lacking mechanistic transparency in their reasoning. If an algorithm flags a lesion as malignant, it cannot provide an interpretable causal biological narrative, creating acute legal and ethical accountability dilemmas when algorithmic errors occur.

[E] Moreover, algorithmic bias represents a persistent clinical hazard. Neural networks trained predominantly on patient datasets from affluent academic medical centers in North America often underperform when deployed in community hospitals serving ethnically diverse or economically disadvantaged populations. Ensuring demographic diversity across training cohorts and validating algorithms through prospective multi-center clinical trials are imperative steps toward safe, equitable diagnostic AI integration.`
    ],
    questions: [
      { type: "tfng", q: "Tell Abu Hureyra was abandoned before the onset of the Younger Dryas cold snap.", answer: "FALSE" },
      { type: "tfng", q: "In wild cereal grasses, a shattering rachis helps seeds disperse naturally in the wind.", answer: "TRUE" },
      { type: "tfng", q: "Mutated non-shattering cereal plants survive better in the wild without human assistance.", answer: "FALSE" },
      { type: "tfng", q: "Early farmers at Abu Hureyra harvested wheat using bone sickles.", answer: "TRUE" },
      { type: "tfng", q: "Skeletons of agricultural humans showed signs of severe arthritis from grinding grain on saddle querns.", answer: "TRUE" },
      { type: "tfng", q: "Permanent grain storage granaries increased the risk of seasonal winter famine.", answer: "FALSE" },
      { type: "tfng", q: "Einkorn wheat is the most widely cultivated commercial crop in Syria today.", answer: "NOT GIVEN" },
      { type: "mcq", q: "What morphological feature distinguishes domesticated wheat from its wild ancestors?", options: ["It grows deep blue flowers", "It has a non-shattering rachis that holds grain firmly to the ear", "It grows underwater in seasonal floods", "Its roots produce natural insect poison"], answer: 1 },
      { type: "mcq", q: "What negative health consequence accompanied animal domestication in early agricultural villages?", options: ["The complete loss of human teeth", "The emergence of zoonotic infectious diseases transmitted from livestock", "Universal blindness from camp smoke", "Chronic scurvy from lack of wild berries"], answer: 1 },
      { type: "mcq", q: "What was the primary chemical emitted by Mount Tambora that caused global cooling?", options: ["Pure nitrogen gas", "Sulfur dioxide that oxidized into sulfuric acid aerosols in the stratosphere", "Methane gas that burned away atmospheric oxygen", "Carbon monoxide that formed thick dark clouds"], answer: 1 },
      { type: "mcq", q: "Why was 1816 called the 'Year Without a Summer'?", options: ["The sun vanished behind the Moon for six months", "Global temperatures dropped, causing killing summer frosts and crop failures", "Continuous forest fires covered the Northern Hemisphere", "A massive meteor blocked the atmosphere"], answer: 1 },
      { type: "completion", q: "The ancient Syrian archaeological site documenting the birth of agriculture is Tell Abu ________.", answer: "Hureyra" },
      { type: "completion", q: "Wild einkorn wheat has a brittle central stem known as a ________.", answer: "rachis" },

      { type: "tfng", q: "Stratospheric sulfuric acid aerosols remain suspended in the upper atmosphere for two to three years.", answer: "TRUE" },
      { type: "tfng", q: "Mary Shelley was inspired to write 'Frankenstein' during the cold, rainy summer of 1816.", answer: "TRUE" },
      { type: "tfng", q: "Karl Drais developed the wooden 'Laufmaschine' because widespread horse starvation demanded alternative transport.", answer: "TRUE" },
      { type: "tfng", q: "Modern diagnostic AI relies exclusively on handcrafted geometric rules written by software engineers.", answer: "FALSE" },
      { type: "tfng", q: "Deep convolutional neural networks are trained end-to-end on millions of annotated medical scans.", answer: "TRUE" },
      { type: "tfng", q: "Diagnostic AI systems suffer from visual search fatigue after working several consecutive hours.", answer: "FALSE" },
      { type: "tfng", q: "AI screening mammography was shown to reduce both false-positive and false-negative diagnoses.", answer: "TRUE" },
      { type: "mcq", q: "What is a major clinical limitation of deep learning AI diagnostic models?", options: ["They require human blood samples to run", "They operate as 'black boxes' without clear transparent explanations for their decisions", "They can only process low-resolution black-and-white photos", "They take several months to evaluate a single scan"], answer: 1 },
      { type: "mcq", q: "Why might a diagnostic AI trained in North American university hospitals fail in rural community clinics?", options: ["Rural computers cannot connect to the internet", "Algorithmic bias caused by lack of demographic diversity in training datasets", "Doctors in rural clinics refuse to use computer monitors", "Radiology scans in community clinics use different radiation types"], answer: 1 },
      { type: "mcq", q: "What technology do modern volcanologists use to track subterranean magma ascent from orbit?", options: ["Barometric mercury balloons", "Satellite InSAR and seismic tremor arrays", "Deep geothermal water drills", "Submarine sonar buoys"], answer: 1 },
      { type: "mcq", q: "What novel did Mary Shelley write during her Swiss holiday in 1816?", options: ["Dracula", "Frankenstein", "Wuthering Heights", "The Time Machine"], answer: 1 },
      { type: "completion", q: "The early two-wheeled wooden bicycle prototype invented in 1817 was named the ________.", answer: "Laufmaschine" },
      { type: "completion", q: "Artificial intelligence systems for medical imaging utilize deep ________ neural networks.", answer: "convolutional" },

      { type: "tfng", q: "Mount Tambora is located on the Indonesian island of Sumbawa.", answer: "TRUE" },
      { type: "tfng", q: "Mount Tambora's 1815 explosion ejected over 100 cubic kilometres of volcanic material.", answer: "TRUE" },
      { type: "tfng", q: "Hunter-gatherers at Abu Hureyra cultivated einkorn wheat during warm tropical weather.", answer: "FALSE" },
      { type: "tfng", q: "InSAR satellite radar allows scientists to detect volcanic surface ground deformation.", answer: "TRUE" },
      { type: "tfng", q: "Medical convolutional neural networks can only analyze dental X-rays.", answer: "FALSE" },
      { type: "tfng", q: "Grinding cereal grains on saddle querns damaged human knee and foot bones.", answer: "TRUE" },
      { type: "tfng", q: "The World Health Organization mandates AI usage for all cancer diagnoses worldwide.", answer: "NOT GIVEN" },
      { type: "mcq", q: "Which volcanic eruption occurred in April 1815?", options: ["Krakatoa", "Mount Vesuvius", "Mount Tambora", "Mount St. Helens"], answer: 2 },
      { type: "mcq", q: "What type of stone tool did early farmers use to grind grains into coarse flour?", options: ["Flint handaxes", "Saddle querns", "Bronze pestles", "Granite rotary water mills"], answer: 1 },
      { type: "mcq", q: "How much did average Northern Hemisphere temperatures fall following the 1815 eruption?", options: ["By up to one degree Celsius", "By ten degrees Celsius", "By twenty-five degrees Celsius", "Temperatures did not change at all"], answer: 0 },
      { type: "mcq", q: "Which medical imaging modality benefits from deep convolutional neural networks?", options: ["Screening mammography and CT scans", "Simple oral thermometers", "Manual stethoscope readings", "Blood pressure cuffs"], answer: 0 },
      { type: "completion", q: "The Indonesian volcanic island where Mount Tambora detonated in 1815 is ________.", answer: "Sumbawa" },
      { type: "completion", q: "The abrupt cold climate period that occurred 12,800 years ago is the Younger ________.", answer: "Dryas" },
      { type: "completion", q: "Deep learning models that hide their internal reasoning are commonly termed 'black ________'.", answer: "boxes" }
    ]
  },
  {
    id: 9,
    title: "Academic Reading Test 9 • Maritime Archaeology, Membrane Physics & Positive Psychology",
    passages: [
      `[A] In the summer of 1962, marine archaeologists diving into the icy, turbid waters of Roskilde Fjord near the town of Skuldelev in Denmark made an astonishing discovery. Scuttled across the narrow Peberrenden navigation channel in the eleventh century to protect the Danish royal capital from naval attacks lay the well-preserved timber skeletons of five distinct Viking vessels, known today as the Skuldelev ships.

[B] The Skuldelev discovery fundamentally reshaped modern understanding of Norse naval architecture. Far from being a monolithic design, Viking shipbuilding was intensely specialized. The find included Skuldelev 2, an oceanic warship measuring thirty metres in length designed to transport sixty warriors across the North Sea, and Skuldelev 1, a broad-beamed, deep-hulled merchant knarr capable of carrying up to twenty-four tons of cargo across the open North Atlantic to Iceland and Greenland.

[C] The secret to Norse naval supremacy lay in the clinker construction method, also known as lapstrake building. Unlike Mediterranean carvel-built ships where hull planks were fitted edge-to-edge over a pre-erected skeleton of ribs, Viking shipwrights built the hull first from the outside in. Split oak planks were overlapped at their edges and fastened together with hand-forged iron rivets, with tarred animal hair inserted into the joints to ensure watertight seals.

[D] This overlapping shell construction bestowed the hull with extraordinary flexibility. In heavy ocean swells, rather than resisting wave forces through rigid mass, the hull flexed and twisted with the contours of the sea, reducing hydrodynamic drag and structural stress. Internal radial frame timbers were lashed to the hull strakes with flexible spruce roots or leather thongs rather than rigid iron bolts, allowing the entire vessel to snake through rolling breakers.

[E] Dendrochronological analysis of the timber rings yielded a surprising historical revelation. Tree-ring matching confirmed that the great warship Skuldelev 2 was constructed not in Scandinavia, but from mature oak trees felled near Dublin, Ireland, in the year 1042. This finding provided tangible archaeological proof of the vast maritime reach and enduring political control exercised by Norse sea kings across the British Isles.`,

      `[A] With global freshwater aquifers depleting at unprecedented rates and municipal populations surging in coastal arid regions, industrial water desalination has emerged as a critical lifeline for hundreds of millions of people. Conventional seawater desalination relies primarily on reverse osmosis (RO), a thermodynamic process where high-pressure pumps force saline water through dense polyamide semipermeable membranes, stripping away dissolved sodium and chloride ions.

[B] Despite decades of optimization, commercial reverse osmosis remains an energy-intensive industrial process. Operating pressures frequently exceed sixty to seventy bar—roughly sixty times atmospheric pressure—demanding vast electrical energy to overcome high osmotic pressures. Furthermore, polymeric polyamide membranes suffer from biofouling by marine microbes and chemical degradation from chlorine disinfectants, requiring frequent chemical cleanings and membrane replacements.

[C] To overcome these thermodynamic constraints, physical chemists are engineering membranes utilizing single-layer graphene. Graphene consists of a two-dimensional honeycomb sheet of sp2-hybridized carbon atoms measuring only a single atom in thickness. Because it possesses negligible physical thickness, water molecules encounter near-zero frictional resistance when passing through sub-nanometer pores perforating the graphene sheet.

[D] Precise pore engineering forms the critical technological barrier in graphene nanofiltration. To effectively desalinate seawater, pores perforated into the graphene lattice must measure between 0.6 and 0.9 nanometers in diameter. Pores of this dimension are large enough to permit the passage of single water molecules, but small enough to physically block hydrated sodium and chloride ions, whose surrounding hydration shells exceed one nanometer across.

[E] Computer simulations and microfluidic laboratory trials reveal that nanoporous graphene membranes can achieve water permeability up to three orders of magnitude higher than conventional polyamide polymers. If scientists can scale defect-free roll-to-roll synthesis of atomic graphene sheets to industrial dimensions, desalination plant energy consumption could plummet by over fifty percent, revolutionizing global water security.`,

      `[A] During the 1960s and 1970s, Hungarian-American psychologist Mihaly Csikszentmihalyi conducted extensive observational studies of artists, chess masters, rock climbers, and surgeons. He was fascinated by a recurring psychological phenomenon: individuals engaged in challenging creative or athletic pursuits routinely became so intensely absorbed in their activities that they lost all awareness of time, fatigue, and personal concerns. Csikszentmihalyi formalized this state of optimal consciousness as 'flow'.

[B] Under Csikszentmihalyi's theoretical model, entering a flow state requires a delicate mathematical balance between two subjective variables: perceived challenge and perceived skill. If the challenge of a task far exceeds an individual's capabilities, the result is acute anxiety; conversely, if skills far outstrip the task's demands, boredom quickly ensues. Flow emerges in the narrow channel where high challenge meets correspondingly high personal competence.

[C] In addition to the skill-challenge equilibrium, flow requires unambiguous proximal feedback and clear distal goals. In activities like rock climbing or playing a musical instrument, every physical movement produces immediate sensory confirmation: a violinist hears instantly whether a pitch is true, and a climber knows immediately whether a handhold is secure. This real-time feedback loop eliminates cognitive ambiguity, focusing conscious attention entirely within the present moment.

[D] Recent neuroimaging investigations have illuminated the neurobiological signatures of the flow state. Rather than activating the entire cerebral cortex, flow is characterized by 'transient hypofrontality'—a temporary down-regulation of neural activity in the prefrontal cortex, specifically within the default mode network (DMN). Because the DMN mediates self-referential thought, ego evaluation, and rumination, its quietening silences the inner self-critical voice, liberating working memory for intense task execution.

[E] Educational theorists and corporate leadership strategists are actively applying flow principles to restructure modern learning and work environments. By decomposing large monolithic projects into calibrated progressive challenges and providing real-time iterative feedback, organizations can cultivate sustained focus, reduce burnout, and foster creative productivity without resorting to coercive external micromanagement.`
    ],
    questions: [
      { type: "tfng", q: "The five Skuldelev Viking vessels were scuttled in a channel to protect Roskilde from naval attack.", answer: "TRUE" },
      { type: "tfng", q: "All five Skuldelev ships were identical warships designed for combat.", answer: "FALSE" },
      { type: "tfng", q: "Viking shipwrights built hulls by overlapping split oak planks fastened with iron rivets.", answer: "TRUE" },
      { type: "tfng", q: "Viking ships had completely rigid hulls that resisted all ocean wave flexure.", answer: "FALSE" },
      { type: "tfng", q: "Dendrochronology confirmed that Skuldelev 2 was built from oak trees felled near Dublin, Ireland.", answer: "TRUE" },
      { type: "tfng", q: "Mediterranean carvel ships were built from the outside in without internal frames.", answer: "FALSE" },
      { type: "tfng", q: "The Danish royal family funded the 1962 Skuldelev archaeological excavation.", answer: "NOT GIVEN" },
      { type: "mcq", q: "What was the purpose of the broad-beamed Viking ship named Skuldelev 1?", options: ["It was a ceremonial funeral barge", "It was a deep-sea merchant cargo ship (knarr) carrying up to 24 tons", "It was a shallow river canoe for salmon fishing", "It was a floating prison for captured soldiers"], answer: 1 },
      { type: "mcq", q: "Why were radial ribs lashed to hull planks with flexible spruce roots in Viking ships?", options: ["Because the Norse had no access to iron", "To allow the vessel's hull to flex safely across ocean swells", "To make the ships sink faster if captured", "To reduce the cost of building boats"], answer: 1 },
      { type: "mcq", q: "What is the primary membrane material currently used in commercial reverse osmosis desalination?", options: ["Woven fiberglass mesh", "Synthetic polyamide polymers", "Pure lead foil", "Perforated rubber sheets"], answer: 1 },
      { type: "mcq", q: "Why do single-layer graphene membranes experience near-zero frictional resistance to water flow?", options: ["They are coated in mineral oil", "Graphene is only one atom thick, minimizing transit distance", "Graphene emits ultrasonic vibrations", "Graphene repels all chemical molecules"], answer: 1 },
      { type: "completion", q: "The traditional Viking method of overlapping hull planks is known as ________ construction.", answer: "clinker" },
      { type: "completion", q: "The science of dating wood by examining tree growth rings is called ________.", answer: "dendrochronology" },

      { type: "tfng", q: "Commercial reverse osmosis desalination requires operating pressures exceeding sixty bar.", answer: "TRUE" },
      { type: "tfng", q: "Graphene is a three-dimensional cube of carbon atoms ten layers thick.", answer: "FALSE" },
      { type: "tfng", q: "Nanopores in graphene must be large enough to let water through but small enough to block salt ions.", answer: "TRUE" },
      { type: "tfng", q: "Graphene membranes could theoretically cut desalination energy consumption by over fifty percent.", answer: "TRUE" },
      { type: "tfng", q: "Mihaly Csikszentmihalyi first formulated the concept of flow in the 1970s.", answer: "TRUE" },
      { type: "tfng", q: "Flow states occur when task challenges greatly exceed an individual's personal skills.", answer: "FALSE" },
      { type: "tfng", q: "Rock climbers and musicians experience immediate sensory feedback during their activities.", answer: "TRUE" },
      { type: "mcq", q: "What neural phenomenon occurs during flow where the prefrontal cortex temporarily reduces activity?", options: ["Cortical hyper-excitation", "Transient hypofrontality", "Synaptic pruning", "Cerebral stroke"], answer: 1 },
      { type: "mcq", q: "Which brain network associated with self-critical rumination is quieted during flow?", options: ["Default mode network (DMN)", "Primary visual cortex", "Sympathetic spinal reflex arc", "Olfactory bulb"], answer: 0 },
      { type: "mcq", q: "What happens when a person's skill level far exceeds the difficulty of the task?", options: ["Severe panic and anxiety", "Immediate unconsciousness", "Boredom", "Deep flow state"], answer: 2 },
      { type: "mcq", q: "In what year was the warship Skuldelev 2 constructed in Dublin according to tree-ring analysis?", options: ["912 CE", "1042 CE", "1215 CE", "1492 CE"], answer: 1 },
      { type: "completion", q: "The hydrated diameter of sodium ions exceeds ________ nanometer across.", answer: "one" },
      { type: "completion", q: "Mihaly Csikszentmihalyi formalized the state of effortless absorption as ________.", answer: "flow" },

      { type: "tfng", q: "The Skuldelev 2 warship carried approximately sixty Norse warriors.", answer: "TRUE" },
      { type: "tfng", q: "Graphene pores measuring between 0.6 and 0.9 nanometers can block dissolved salt ions.", answer: "TRUE" },
      { type: "tfng", q: "Reverse osmosis membranes never experience biofouling from marine microbes.", answer: "FALSE" },
      { type: "tfng", q: "Flow state is characterized by complete hyper-awareness of time passing.", answer: "FALSE" },
      { type: "tfng", q: "Viking shipbuilders inserted tarred animal hair into plank joints for waterproofing.", answer: "TRUE" },
      { type: "tfng", q: "Polyamide reverse osmosis membranes can withstand unlimited chlorine exposure without damage.", answer: "FALSE" },
      { type: "tfng", q: "Csikszentmihalyi conducted research at the University of Chicago.", answer: "NOT GIVEN" },
      { type: "mcq", q: "Where were the five Viking ships discovered in 1962?", options: ["Thames Estuary near London", "Roskilde Fjord in Denmark", "Reykjavik Harbor in Iceland", "Oslo Fjord in Norway"], answer: 1 },
      { type: "mcq", q: "What is the primary carbon atom hybridization present in a single sheet of graphene?", options: ["sp3 diamond lattice", "sp2 planar honeycomb lattice", "Linear sp triple-bond chain", "Amorphous charcoal powder"], answer: 1 },
      { type: "mcq", q: "Which two psychological variables must balance to enter a flow state?", options: ["Perceived challenge and perceived personal skill", "Physical heart rate and ambient air temperature", "Blood sugar and hours of sleep", "Social status and financial income"], answer: 0 },
      { type: "mcq", q: "What Viking ship type was designed specifically for long-distance North Atlantic ocean trading?", options: ["Drakkar longship", "Knarr", "Faering rowboat", "Snekkja raider"], answer: 1 },
      { type: "completion", q: "The fjord in Denmark where the five Viking ships were scuttled is ________ Fjord.", answer: "Roskilde" },
      { type: "completion", q: "Water purification by pushing water through a membrane against osmotic pressure is reverse ________.", answer: "osmosis" },
      { type: "completion", q: "During flow, the down-regulation of the prefrontal cortex quiets the inner self-________ voice.", answer: "critical" }
    ]
  },
  {
    id: 10,
    title: "Academic Reading Test 10 • Ecosystem Ecology, Print History & Quantum Computing",
    passages: [
      `[A] In 1995, following an absence of seven decades, wildlife biologists released fourteen gray wolves (Canis lupus) into Yellowstone National Park. Eradicated by government predator-control campaigns in the 1920s, the apex predator's prolonged disappearance had triggered severe ecological imbalances. The subsequent recovery of Yellowstone has become the world's most celebrated case study in trophic cascades—the ecological ripple effects triggered by changing top predator abundance.

[B] During the seventy-year absence of wolves, Yellowstone's elk (Cervus canadensis) population exploded, tripling in numbers. Uninhibited by fear of predation, elk herds browsed heavily on young willow, aspen, and cottonwood saplings along river valleys. Consequently, riparian riverbanks were stripped bare of stabilizing vegetation, provoking widespread riverbank erosion, warming stream waters, and collapsing habitats for migratory songbirds and amphibians.

[C] The reintroduction of wolves initiated an immediate behavioral transformation termed the 'ecology of fear'. Rather than merely reducing elk numbers through direct predation, wolves altered elk grazing patterns. Elk began avoiding deep river gorges, blind valleys, and riparian zones where they were vulnerable to pack ambushes. Freed from chronic overbrowsing, riparian willow stands recovered with astonishing speed, growing fourfold in height within a decade.

[D] The revitalization of riverside willows catalyzed a dramatic resurgence of North American beavers (Castor canadensis). Beavers require willow and aspen branches for food and lodge construction. In 1995, Yellowstone supported only a single beaver colony; fifteen years later, the park housed over twelve thriving colonies. Beaver dams slowed river currents, created extensive wetland reservoirs that recharged groundwater tables, and established tranquil sediment-settling pools that nourished trout and waterfowl.

[E] Crucially, the return of wolves altered the physical geography of Yellowstone's waterways. Stabilized by dense regenerated root matrices from riparian trees and buffered by beaver dams, eroding riverbanks solidified. River channels developed tighter meanders, cut deeper pools, and formed stable riffles, demonstrating how the presence of an apex carnivore can reshape physical landscape topography across entire river basins.`,

      `[A] In the mid-fifteenth century, in the German Rhine valley city of Mainz, a goldsmith and venture capitalist named Johannes Gutenberg synthesized several existing artisan technologies to create a mechanical innovation that reshaped human history: the movable metal type printing press. Prior to Gutenberg, Western book production was monopolized by monastic scriptoria, where scribes spent months manually copying manuscripts in iron-gall ink on animal vellum, rendering books unaffordable luxuries.

[B] Gutenberg's technological triumph rested upon four interconnected innovations. First, he developed an adjustable hand mold, allowing a punch-cutter to cast thousands of identical, interchangeable pieces of metal type from an alloy of lead, tin, and antimony. This specific metallurgical formulation possessed a critical property: it expanded slightly as it cooled in the matrix, yielding crisp, razor-sharp letter edges that did not deform under heavy press pressure.

[C] Second, Gutenberg reformulated printing ink. Traditional water-based inks pooled on metal surfaces rather than adhering evenly. Gutenberg formulated a thick, viscous oil-based ink utilizing boiled linseed oil and soot, which adhered smoothly to metallic type faces and transferred cleanly onto paper without bleeding. Third, he adapted the heavy wooden screw press traditionally used in Mediterranean winemaking and olive pressing, enabling uniform mechanical downward pressure across broad sheets of dampened rag paper.

[D] The commercial impact of Gutenberg's press was immediate and explosive. By 1455, Gutenberg completed his masterwork—the 42-Line Bible—printing approximately 180 copies in the time it would have taken a single monastic scribe to produce one. Within five decades, the technology diffused across over two hundred European cities. By 1500, printing workshops had produced an estimated twenty million volumes—more books than all of Europe's scribes had written in the preceding millennium.

[E] The dissemination of printed vernacular texts dismantled the Catholic Church's Latin monopoly on literacy and knowledge. In 1517, Martin Luther's Ninety-Five Theses were translated into German, printed in thousands of broadsheets, and distributed across Europe within weeks, sparking the Protestant Reformation. Concurrently, the standardized printing of scientific treatises and astronomical charts enabled researchers to replicate empirical experiments, igniting the Scientific Revolution.`,

      `[A] At the subatomic scale, the deterministic laws of classical Newtonian physics surrender to the counterintuitive principles of quantum mechanics. In conventional digital computers, information is encoded in binary digits, or bits, which exist in one of two definite states: zero or one. In contrast, quantum computers process quantum bits, or qubits, which exploit two foundational quantum phenomena: superposition and quantum entanglement.

[B] Superposition allows a qubit to exist simultaneously as a linear combination of both zero and one. While a classical two-bit register can store only one of four possible states (00, 01, 10, or 11) at any given moment, a two-qubit quantum register exists in a superposition of all four states simultaneously. As the number of entangled qubits scales linearly, the computational state space expands exponentially: a quantum computer possessing three hundred perfectly entangled qubits could theoretically process more simultaneous states than there are subatomic particles in the observable universe.

[C] Quantum entanglement—which Albert Einstein famously termed 'spooky action at a distance'—links the states of multiple qubits so that the state of one instantly dictates the state of another, regardless of physical distance. Quantum algorithms, such as Peter Shor's 1994 algorithm for prime factor decomposition, exploit quantum interference to amplify correct computational pathways while canceling incorrect outcomes through destructive wave interference. Shor's algorithm proved that a sufficiently powerful quantum computer could effortlessly crack RSA encryption, the mathematical backbone of global financial cybersecurity.

[D] The central impediment to constructing practical quantum processors is quantum decoherence. Qubits are extraordinarily fragile quantum systems, typically implemented using superconducting Josephson junctions chilled to near absolute zero (-273.14°C) or laser-trapped atomic ions. Stray thermal fluctuations, electromagnetic noise, or cosmic radiation instantly collapse superpositions into classical random errors, destroying the quantum computation within microseconds.

[E] To counteract decoherence, researchers are developing quantum error correction (QEC) codes. Because quantum mechanics forbids directly measuring a qubit without collapsing its superposition (the No-Cloning Theorem), QEC distributes the quantum information of a single logical qubit across hundreds of physical entangled helper qubits. Achieving fault-tolerant quantum computing will unlock transformative advances in simulating complex molecular chemistry for drug discovery, optimizing global supply chain logistics, and designing revolutionary room-temperature superconductors.`
    ],
    questions: [
      { type: "tfng", q: "Gray wolves were completely absent from Yellowstone National Park for roughly seventy years.", answer: "TRUE" },
      { type: "tfng", q: "In the absence of wolves, Yellowstone's elk population declined sharply due to starvation.", answer: "FALSE" },
      { type: "tfng", q: "Elk avoided grazing in deep river valleys after wolves were reintroduced.", answer: "TRUE" },
      { type: "tfng", q: "Riparian willow plants grew four times taller within a decade of wolf reintroduction.", answer: "TRUE" },
      { type: "tfng", q: "Yellowstone supported over fifty thriving beaver colonies when wolves were reintroduced in 1995.", answer: "FALSE" },
      { type: "tfng", q: "Beaver dams helped slow river currents and recharge local groundwater tables.", answer: "TRUE" },
      { type: "tfng", q: "Wolves have been reintroduced to all national parks in the United States.", answer: "NOT GIVEN" },
      { type: "mcq", q: "What is the ecological term for ripple effects caused by changes in top predator abundance?", options: ["Biomagnification", "Trophic cascade", "Competitive exclusion", "Mutualistic succession"], answer: 1 },
      { type: "mcq", q: "How did the return of wolves affect the physical geography of Yellowstone's rivers?", options: ["Rivers dried up and disappeared", "Riverbanks stabilized, channels formed tighter meanders and deeper pools", "Rivers widened and turned into straight canals", "Water in the rivers turned acidic"], answer: 1 },
      { type: "mcq", q: "What metal alloy did Gutenberg use to cast movable type pieces that expanded slightly upon cooling?", options: ["Pure copper and zinc", "Lead, tin, and antimony", "Iron and nickel", "Titanium and silver"], answer: 1 },
      { type: "mcq", q: "Why did Gutenberg replace water-based ink with linseed oil and soot ink?", options: ["Water ink evaporated too quickly in cold weather", "Water-based ink pooled on metal type and ran, while oil ink adhered smoothly", "Linseed oil was cheaper than water", "Oil ink glowed in the dark"], answer: 1 },
      { type: "completion", q: "The behavioral transformation where elk avoided dangerous grazing areas is the ecology of ________.", answer: "fear" },
      { type: "completion", q: "Gutenberg's 42-Line Bible was completed around the year ________.", answer: "1455" },

      { type: "tfng", q: "Gutenberg adapted the mechanical screw press used in winemaking for his printing press.", answer: "TRUE" },
      { type: "tfng", q: "European printing presses produced approximately twenty million books by the year 1500.", answer: "TRUE" },
      { type: "tfng", q: "The printing press helped diffuse Martin Luther's Ninety-Five Theses across Europe within weeks.", answer: "TRUE" },
      { type: "tfng", q: "Classical computer bits can exist simultaneously as both zero and one.", answer: "FALSE" },
      { type: "tfng", q: "Quantum superposition allows qubits to exist in linear combinations of states.", answer: "TRUE" },
      { type: "tfng", q: "Shor's quantum algorithm was formulated to factor large prime numbers and challenge RSA encryption.", answer: "TRUE" },
      { type: "tfng", q: "Superconducting qubits operate at normal room temperature without special cooling.", answer: "FALSE" },
      { type: "mcq", q: "What subatomic phenomenon did Albert Einstein famously call 'spooky action at a distance'?", options: ["Quantum decoherence", "Quantum entanglement", "Wave-particle duality", "Radioactive decay"], answer: 1 },
      { type: "mcq", q: "What environmental factor can cause quantum decoherence and destroy qubit calculations?", options: ["Stray thermal heat, electromagnetic noise, and cosmic radiation", "High atmospheric oxygen levels", "Bright visible room light", "Ordinary radio sound waves"], answer: 0 },
      { type: "mcq", q: "Why can't researchers measure a qubit directly to detect computational errors?", options: ["Direct measurement collapses the superposition into a classical state", "Qubits are too small for any microscope", "Direct measurement causes the processor to catch fire", "Qubit measurements are illegal under international law"], answer: 0 },
      { type: "mcq", q: "What was the estimated number of copies printed for Gutenberg's celebrated 42-Line Bible?", options: ["Only two copies", "Approximately 180 copies", "Ten thousand copies", "One million copies"], answer: 1 },
      { type: "completion", q: "Quantum computers chilled near absolute zero operate at -273.14 degrees ________.", answer: "Celsius" },
      { type: "completion", q: "The mathematical algorithm developed by Peter ________ in 1994 can factor large numbers.", answer: "Shor" },

      { type: "tfng", q: "Before Gutenberg, European books were copied by hand on animal vellum parchment.", answer: "TRUE" },
      { type: "tfng", q: "Beaver populations at Yellowstone declined after wolves were reintroduced.", answer: "FALSE" },
      { type: "tfng", q: "A classical 2-bit register can store all four binary states at the exact same instant.", answer: "FALSE" },
      { type: "tfng", q: "Superconducting qubits are frequently made using Josephson junctions.", answer: "TRUE" },
      { type: "tfng", q: "Decoherence happens when a quantum state collapses within microseconds due to noise.", answer: "TRUE" },
      { type: "tfng", q: "Elk in Yellowstone continued to browse riparian riverbanks heavily after 1995.", answer: "FALSE" },
      { type: "tfng", q: "Johannes Gutenberg died a wealthy multi-millionaire recognized across Europe.", answer: "NOT GIVEN" },
      { type: "mcq", q: "Which animal species returned to Yellowstone and built multiple wetland dams after willow recovery?", options: ["Grizzly bears", "North American beavers", "Moose", "River otters"], answer: 1 },
      { type: "mcq", q: "What language did the Catholic Church use that monopolized formal literacy before the press?", options: ["Classical Greek", "Latin", "Old German", "French"], answer: 1 },
      { type: "mcq", q: "What fundamental theorem of quantum mechanics prohibits copying an unknown quantum state?", options: ["Heisenberg Uncertainty Principle", "No-Cloning Theorem", "Pauli Exclusion Principle", "Schrödinger's Wave Equation"], answer: 1 },
      { type: "mcq", q: "In what century did Gutenberg introduce his movable metal type press in Mainz?", options: ["Twelfth century", "Mid-fifteenth century", "Seventeenth century", "Nineteenth century"], answer: 1 },
      { type: "completion", q: "Yellowstone's elk belong to the biological species Cervus ________.", answer: "canadensis" },
      { type: "completion", q: "The German city where Gutenberg established his first printing press was ________.", answer: "Mainz" },
      { type: "completion", q: "QEC stands for Quantum Error ________.", answer: "Correction" }
    ]
  }
];
